DATABASE_URL_AC=postgres://postgres:sd1234!@localhost:5432/admin-console?sslmode=disable
DATABASE_CONNECTION_LIFETIME=5
DATABASE_MAX_CONNS=20
DATABASE_MIN_CONNS=1

LOG_FILE=logs/admin-console.log
LOG_DATE_TIME=true

NODE_ID=1